name: code_challenge
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: ^3.5.1 

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^4.0.0 
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
 
  assets:  
    - assets/images/
 